services:

  postgres:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: pass
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres