"""video model upd

Revision ID: 1acd3ec18ab2
Revises: 3e6f7dcd9899
Create Date: 2026-03-06 13:09:22.699003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1acd3ec18ab2'
down_revision: Union[str, Sequence[str], None] = '3e6f7dcd9899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('subtitles', sa.Text(), nullable=True))
    op.add_column('videos', sa.Column('subtitles_ts', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'subtitles_ts')
    op.drop_column('videos', 'subtitles')
    # ### end Alembic commands ###
