"""video model upd

Revision ID: 3e6f7dcd9899
Revises: eab176585976
Create Date: 2026-03-06 12:27:02.754749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6f7dcd9899'
down_revision: Union[str, Sequence[str], None] = 'eab176585976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'source_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
