"""add subtitles to the video sql model

Revision ID: 474cd3a2e95e
Revises: bac80872f5fe
Create Date: 2026-03-04 20:31:41.745917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '474cd3a2e95e'
down_revision: Union[str, Sequence[str], None] = 'bac80872f5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('subtitles', sa.Text(), nullable=True),
    sa.Column('subtitles_with_timestamps', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_source_url'), 'video', ['source_url'], unique=True)
    op.drop_index(op.f('ix_video_youtube_source_url'), table_name='video_youtube')
    op.drop_table('video_youtube')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_youtube',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('video_youtube_pkey'))
    )
    op.create_index(op.f('ix_video_youtube_source_url'), 'video_youtube', ['source_url'], unique=True)
    op.drop_index(op.f('ix_video_source_url'), table_name='video')
    op.drop_table('video')
    # ### end Alembic commands ###
