"""video model upd

Revision ID: 6c16ecf24a9d
Revises: aea1411862e0
Create Date: 2026-03-06 11:37:01.351438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c16ecf24a9d'
down_revision: Union[str, Sequence[str], None] = 'aea1411862e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'canonical_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('videos', 'raw_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('videos', 'canonical_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
