"""add subtitles to the video sql model

Revision ID: a45067d6f4f4
Revises: 474cd3a2e95e
Create Date: 2026-03-04 20:47:34.441538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45067d6f4f4'
down_revision: Union[str, Sequence[str], None] = '474cd3a2e95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('subtitles_ts', sa.Text(), nullable=True))
    op.drop_column('video', 'subtitles_with_timestamps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('subtitles_with_timestamps', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('video', 'subtitles_ts')
    # ### end Alembic commands ###
