"""updated video sql model

Revision ID: bf4baebdb397
Revises: a45067d6f4f4
Create Date: 2026-03-06 10:11:06.807497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf4baebdb397'
down_revision: Union[str, Sequence[str], None] = 'a45067d6f4f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('default_language', sa.String(length=16), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_videos_platform_external_id')
    )
    op.create_index('ix_videos_created_at', 'videos', ['created_at'], unique=False)
    op.create_index('ix_videos_platform_external_id', 'videos', ['platform', 'external_id'], unique=False)
    op.drop_index(op.f('ix_video_source_url'), table_name='video')
    op.drop_table('video')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subtitles', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('subtitles_ts', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('video_pkey'))
    )
    op.create_index(op.f('ix_video_source_url'), 'video', ['source_url'], unique=True)
    op.drop_index('ix_videos_platform_external_id', table_name='videos')
    op.drop_index('ix_videos_created_at', table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
