"""subtitles model updated

Revision ID: d90046f9d6c3
Revises: 1acd3ec18ab2
Create Date: 2026-03-07 16:35:55.196846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90046f9d6c3'
down_revision: Union[str, Sequence[str], None] = '1acd3ec18ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_subtitles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('subtitles', sa.Text(), nullable=True),
    sa.Column('subtitles_ts', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.drop_column('videos', 'subtitles')
    op.drop_column('videos', 'subtitles_ts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('subtitles_ts', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('subtitles', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('video_subtitles')
    # ### end Alembic commands ###
