"""video model upd

Revision ID: eab176585976
Revises: 6c16ecf24a9d
Create Date: 2026-03-06 11:49:22.700025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab176585976'
down_revision: Union[str, Sequence[str], None] = '6c16ecf24a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('source_url', sa.Text(), nullable=False))
    op.drop_column('videos', 'original_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('original_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('videos', 'source_url')
    # ### end Alembic commands ###
